#!/bin/sh
# Don't forget disable autostart service
# Uncomment starting services compatible with FreeBSD/Ubuntu
case $1 in
start)
#        /usr/local/etc/rc.d/ftpd onestart
#	/usr/sbin/service vsftpd start
        ;;
stop)
#        /usr/local/etc/rc.d/ftpd onestop
#	/usr/sbin/service vsftpd stop
        ;;
status)
	#service vsftpd status | grep running && exit 0
	#service vsftpd status | grep running && exit 0
	# FreeBSD
	#service vsftpd onestatus | grep stopped && exit 1
	#service vsftpd onestatus | grep stopped && exit 1
	;;
esac

exit 0
