---

- hosts: firewall
  remote_user: spec
  become: yes
  become_user: root
  become_method: su
  tasks:
  - name: "Set hostname"
    hostname: name="firewall.corp{{ user_x }}.un"
  - name: "Setup network"
    register: interfaces
    vars:
      dns_server: 172.16.0.1
    template:  src=fw_interfaces.j2 dest=/etc/network/interfaces
  - name: "Restart interfaces"
    shell: "ifdown eth0; ifdown eth1; sleep 1; ifup eth0; ifup eth1"
  - name: "Set time"
    register: ntp
    shell: "ntpdate pool.ntp.org"
  - name: "Dist upgrade"
    apt: update_cache=yes upgrade=dist force=yes autoremove=yes
    register: dist_upgrade
    when: ntp|success

  # NTP
  - name: "Install NTPD"
    apt: name=openntpd force=yes

  # ISC DHCP
  - name: "Install DHCP"
    register: install_dhcp
    apt: name=isc-dhcp-server
    when: "( dist_upgrade | success ) or (dist_upgrade.changed == false)"
  - name: "Configure DHCP"
    template: src="{{item.src}}" dest="{{item.dest}}"
    with_items:
      - { src: "dhcpd.conf.j2", dest: "/etc/dhcp/dhcpd.conf" }
      - { src: "dhcpd_vars.j2", dest: "/etc/default/isc-dhcp-server" }
  - name: "Restart DHCP"
    service: name="isc-dhcp-server" state=restarted

  # NAT
  - name: "Setup iptables"
    apt: name=iptables-persistent force=yes
    when: "( dist_upgrade | success ) or (dist_upgrade.changed == false)"
  - name: "Setup sysctl"
    template: src=sysctl.conf.j2 dest=/etc/sysctl.conf
  - name: "Activate sysctl "
    shell: "sysctl -p /etc/sysctl.conf"
  - name: "Add rules"
    shell: "iptables -t nat -F; iptables -t nat -A POSTROUTING -s 192.168.{{user_x}}.0/24 -o eth0 -j SNAT --to-source=172.16.0.11"
  - name: "Save rules"
    shell: "service iptables-persistent save"

