---
- name: Setup un3 server
  tags: [ module1, server ]
  hosts: [ un3_server ]
  tasks:
    - name: Basic setup
      include_role:
        name: basic
    - name: Sync time
      include_role:
        name: ntpdate
    - name: Setup network
      vars:
        interfaces_template: templates/interfaces/server_initial.j2  
        dns_server: "192.168.{{ user_x }}.1" 
        restart_interfaces: 
          - "{{ interfaces.internal }}"
      include_role:
        name: network
    - name: Setup postfix
      include_role:
        name: postfix
      vars:
        postfix_setup: local
